[package]
name = "before-effects"
version = "0.1.0"
authors = ["Stephan Göppentin <dedda102@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
opencl3 = "0.1"
yatl = "0.1"